
services:
  frontend:
    build:
      context: ./frontend  # Path to the frontend folder
    ports:
      - "3000:3000"  # Expose the frontend on port 3000
    volumes:
      - ./frontend:/usr/src/app  # Sync frontend code with container
      - /usr/src/app/node_modules
    depends_on:
      - backend  # Ensure backend is up before frontend starts
   
      
  backend:
    build:
      context: ./backend  # Path to the backend folder
    ports:
      - "5000:5000"  # Expose the backend on port 5000
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb  # Use "db" as the hostname
    depends_on:
      - db  # Wait for the db service to start
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules  

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432 for external access

volumes:
  pgdata:
