version: '3'
services:

  nginx:
    build:
      context: ./nginx  # Assuming you have a Dockerfile in ./nginx
    ports:
      - "80:80"  # Expose Nginx on port 80 for external access
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend  # Build the frontend from the frontend directory
    depends_on:
      - backend  # Wait for the backend to start before frontend

  backend:
    build:
      context: ./backend  # Build the backend from the backend directory
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb  # Database connection string
    depends_on:
      - db  # Ensure the database starts before the backend
    
  db:
    image: postgres:17  # Use official PostgreSQL image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data in a Docker volume

volumes:
  pgdata:  # Define the persistent volume for PostgreSQL
