# Use an official Node.js image as the base image
FROM node:22

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install the dependencies inside the container
RUN npm install

# Install nodemon globally for development
RUN npm install -g nodemon

# Copy the rest of the application code to the container
COPY . .

# Expose the port the backend will run on
EXPOSE 5000

# Use nodemon to start the application
CMD ["nodemon", "server.js"]

